os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty

osx_image: xcode9.3
before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor;
            sudo chmod -R a+rx /usr/;
        fi

script:
    - swift build -c release
    ##- swift test
##deploy:
##  provider: script
##  script: vapor cloud deploy
##  on:
##    branch: master
notifications:
 slack:
   rooms:
     - bond-onlab:fNiYup7w9i7OgDrFuA3dZpE8#backend
   template:
     - "https://www.youtube.com/watch?v=DFloZbT99oE"
     - "%{result}"
 email: false
